name: sla
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - opencv
  - tensorboard
  - wandb
  - matplotlib
  - onnx
  - onnxruntime
  - tqdm
  - loguru
  - pip:
    - commonmark
    - ninja
    - onnx-simplifier
    - pycocotools
    - pygments
    - rich
    - thop
